version: '3'

services:
  web:
    build: .
    command: ./bin/server
    ports:
      - 5000:5000
      - 3035:3035
    volumes:
      - .:/myapp
      - bundle_install:/bundle
    environment:
      RAILS_ENV: development
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    
volumes:
  mysql-data:
    driver: local
  bundle_install:
    driver: local

